package example;


/**
* example/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/RepositoriosComputoDistribuido/CORBA/CorbaFiboInterface/CorbaFiboInterface/src/fibonacci.idl
* lunes 19 de julio de 2021 05:44:38 PM CDT
*/

public interface FibonacciOperations 
{

  /* Codigo fibonacci CORBA
    * in: elvalor del parametro se le envía desde el cliente al servidor
    * long: -231...231-1 (32 bits)
    * número: nombre de la variable
    */
  String generar (int numero);
} // interface FibonacciOperations
